// Code generated by MockGen. DO NOT EDIT.
// Source: cookie.go

// Package main is a generated GoMock package.
package main

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCookieManager is a mock of CookieManager interface.
type MockCookieManager struct {
	ctrl     *gomock.Controller
	recorder *MockCookieManagerMockRecorder
}

// MockCookieManagerMockRecorder is the mock recorder for MockCookieManager.
type MockCookieManagerMockRecorder struct {
	mock *MockCookieManager
}

// NewMockCookieManager creates a new mock instance.
func NewMockCookieManager(ctrl *gomock.Controller) *MockCookieManager {
	mock := &MockCookieManager{ctrl: ctrl}
	mock.recorder = &MockCookieManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCookieManager) EXPECT() *MockCookieManagerMockRecorder {
	return m.recorder
}

// DeleteSession mocks base method.
func (m *MockCookieManager) DeleteSession(sessionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteSession", sessionID)
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockCookieManagerMockRecorder) DeleteSession(sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockCookieManager)(nil).DeleteSession), sessionID)
}

// GetSession mocks base method.
func (m *MockCookieManager) GetSession(sessionID string) http.CookieJar {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", sessionID)
	ret0, _ := ret[0].(http.CookieJar)
	return ret0
}

// GetSession indicates an expected call of GetSession.
func (mr *MockCookieManagerMockRecorder) GetSession(sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockCookieManager)(nil).GetSession), sessionID)
}

// NewSession mocks base method.
func (m *MockCookieManager) NewSession(sessionID string) http.CookieJar {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSession", sessionID)
	ret0, _ := ret[0].(http.CookieJar)
	return ret0
}

// NewSession indicates an expected call of NewSession.
func (mr *MockCookieManagerMockRecorder) NewSession(sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSession", reflect.TypeOf((*MockCookieManager)(nil).NewSession), sessionID)
}

// MockSessionDeleter is a mock of SessionDeleter interface.
type MockSessionDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockSessionDeleterMockRecorder
}

// MockSessionDeleterMockRecorder is the mock recorder for MockSessionDeleter.
type MockSessionDeleterMockRecorder struct {
	mock *MockSessionDeleter
}

// NewMockSessionDeleter creates a new mock instance.
func NewMockSessionDeleter(ctrl *gomock.Controller) *MockSessionDeleter {
	mock := &MockSessionDeleter{ctrl: ctrl}
	mock.recorder = &MockSessionDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionDeleter) EXPECT() *MockSessionDeleterMockRecorder {
	return m.recorder
}

// DeleteSession mocks base method.
func (m *MockSessionDeleter) DeleteSession(sessionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteSession", sessionID)
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockSessionDeleterMockRecorder) DeleteSession(sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockSessionDeleter)(nil).DeleteSession), sessionID)
}
