name: golang-lint

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: -v --timeout=5m

      - name: install revive
        run: go install github.com/mgechev/revive@v1.2.4

      - name: run revive
        run: revive -config .revive.toml -formatter friendly ./...